GET http://localhost:8081/yeah

> {%
 client.test("test-hello",function(){
  client.log("测试/hello接口");
  client.log(response.body);
  client.log(JSON.stringify(response.body));
  client.assert(response.status === 200,"false");
  client.assert(response.body === "yeah!","false");
 });
 %}
###

GET http://localhost:8081/test/redis/set/123/test
Accept: application/json

###

GET http://localhost:8081/redis/get/121163536872378368
Accept: application/json

###